CREATE DATABASE TestDB;
SET DATABASE TestDB;
CREATE TABLE Estudiante (ID INTEGER, Nombre VARCHAR(30), Apellido VARCHAR(30), Nota DOUBLE);
INSERT INTO Estudiante (1, "Ana", "Gomez", 90.5);
INSERT INTO Estudiante (2, "Luis", "Perez", 78.0);
INSERT INTO Estudiante (3, "Maria", "Lopez", 95.0);
INSERT INTO Estudiante (4, "Carlos", "Mora", 65.5);
SELECT * FROM Estudiante;
SELECT * FROM Estudiante WHERE ID = 2;
SELECT Nombre FROM Estudiante WHERE Nota = 95.0;
SELECT * FROM Estudiante ORDER BY Nota DESC;
UPDATE Estudiante SET Nota = 88.0 WHERE ID = 4;
SELECT * FROM Estudiante WHERE ID = 4;
CREATE INDEX Estudiante_ID ON Estudiante(ID) OF TYPE BTREE;
SELECT * FROM Estudiante WHERE ID = 3;
DELETE FROM Estudiante WHERE ID = 1;
SELECT * FROM Estudiante;
CREATE DATABASE TestDB;
SET DATABASE NoExiste;
INSERT INTO TablaFalsa (1, "test");
INSERT INTO Estudiante (1, "Solo");
INSERT INTO Estudiante (2, "Duplicado", "Test", 70.0);
SELECT ColumnaFalsa FROM Estudiante;
DROP TABLE Estudiante;
SELECT * FROM Estudiante WHERE ColumnaInexistente = 1;